### ISSUE TITLE
Get canned responses from API to the Redux store (load on first page load)

### ISSUE THREAD

**Issue by madasan** [mozilla/m-response#325]
Cannot move into QA's bucket until there is data to test on. @johngian Can you add same/ fake canned responses data into the staging env?

**Comment by viorelaioia** [comment]
@madasan , @M-erb , can you clarify what exactly we should verify for this ticket?
So far, I tested that the canned responses that we added via admin are available in the application, under the corresponding categories.
One thing I noticed is that the canned responses categories were not updated to show the new added response (via admin) after a page refresh on the Respond page. I had to navigate to homepage and come back to the respond page in order to get the newly added canned response. Should we fix that?

**Comment by M-erb** [comment]
@viorelaioia As stated in the issue title "(load on first page load)" the canned responses by design only load on the homepage. So its a feature not a bug ;-) As for what to test, to the best of my knowledge, is exactly what you did that the canned responses auto-update on home page and show up within the application. Thank you viorelaioia!
