### ISSUE TITLE
Karma is enabled for moderation

### ISSUE THREAD

**Issue by madasan** [mozilla/m-response#334]

**Comment by madasan** [comment]
Karma points are awarded as follows:

Getting a response approved - 1 point (Karma awarded the author of the response)

Moderating a response (Karma awarded to the author of the moderation)
- The response has no moderations - 1 point
- The response has 1 moderation - 2 points
- The response has 2 moderations - 3 points

Karma points are only visible to the users themselves

**Comment by rleitan** [comment]
> Getting a response approved - 1 point (Karma awarded the author of the response)
>  
Actual result: the user who approved the response was awarded with 1 karma point instead of the response author

> Moderating a response (Karma awarded to the author of the moderation)
> 
> The response has no moderations - 1 point
>
Actual result: 2 points (contributor account)

>  The response has 1 moderation - 2 points
>
Actual result: 3 points (moderator account)

> * The response has 2 moderations - 3 points
Actual result: 1 point ( super moderator account)

Besides, I think it's unclear how many karma points will be gained when moderating a response. e.g. K+10 is displayed in the right side on "Response moderated" notification banner and the max number of karma points that could be gained is 3 as explained above.
![2019-09-26_17h37_18](https://user-images.githubusercontent.com/41474886/65697999-84cf6500-e084-11e9-92fe-5c0ae18608e5.png)

@M-erb @madasan @vbabiy

**Comment by madasan** [comment]
The karma points displayed in the moderation list should look as following:
- Response has not been moderated yet (no checkmarks) - K1 point 
- Response has been moderated once (1 checkmark) -  K2 points
- Response has been moderated twice (2 checkmarks) - K3 points

This should also be reflected in the notification banner after the response has been moderated

**Comment by rleitan** [comment]
blocked by https://github.com/mozilla/m-response/issues/415
