### ISSUE TITLE
Skip respond button is not working

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#389]
[Environment];
Windows 10 - Firefox, Chrome
iOS tablet - 12.4 - Safari

[Precondition]:
Have only one review for a language (e.g. one review available for en-US)

[STR]:
1.Go to https://mresponse-staging.herokuapp.com/respond/
2.Click "Skip" button

[Expected result]:
The review should be skipped and no review should be displayed if there aren't any 

[Actual result]:
Nothing happens

[Note]:
The Skip button works when there are more than one reviews
@madasan @mcroud

**Comment by mcroud** [comment]
There is something a bit squiffy here :)

It might be difficult to see from the gif below, but the Skip link seems to "not register" on some occasions, after multiple attempts it works but I am still not able to access the ghosted response below.

The ghosted response represents the next response in the queue, clicking Skip link should turn that bottom ghosted response into the current one for a user to respond to. 

![Untitled5](https://user-images.githubusercontent.com/42435754/65058341-04b24c80-d96c-11e9-8a8a-56b58e292eaa.gif)

**Comment by mcroud** [comment]
I'm not aware if there has been any prior discussion to how "skip" should work in the event that there is no other response to skip, but I'll add my suggestion :)

In the event that there is nothing to skip to, I think hiding "skip" would cause less confusion. The common alternative would be for it to be greyed out but that might make people think that they need to do _something_ in order to make it enabled?

As we expose the number of responses in the queue on the dashboard it shouldn't be a complete surprise to users that they might be at the bottom of the pile (I could be wrong though?) 

There were early design suggestions for a Respond queue, similar to the Moderate queue which might solve this problem more eloquently in the future :)

<img width="462" alt="Screenshot 2019-09-18 at 16 51 32" src="https://user-images.githubusercontent.com/42435754/65164343-9eddc780-da34-11e9-98e1-4662fe568e0d.png">
