### ISSUE TITLE
Permission restriction per locale

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/m-response#538]
Mod1 and mod2 access right now are not restricted to a specific locale. Someone with mod2 access can bypass any moderation for any locales. This should be changed so a moderator can be restricted to a certain locale.

**Comment by LeoMcA** [comment]
Since https://github.com/mozilla/sumo-project/issues/514 mod2s should be slightly restricted in locales they don't have permissions in. When they post in such a locale, they'll be treated as if they were a mod1 (so review skips moderation, but doesn't get submitted).

Do you have an example of a mod2 skipping staff approval as well in a locale they shouldn't?

**Comment by kelimuttu** [comment]
got it. In that case, can we add multiple locale permission?

**Comment by LeoMcA** [comment]
> multiple locale permission

What do you mean by this? Users can already be made mod2 in multiple locales

**Comment by kelimuttu** [comment]
Just to clarify, 

What I mean is, for example, say I want to be an English and Japanese mod2. Will my mod2 permission restricted to those 2 locales?

**Comment by LeoMcA** [comment]
Yes, it can be - the "Permissions in locales" field sets which of the user's locales they'll have mod2 permission in, they'll have mod1 in every other locale. So if a user has declared their locales to be en, jp and de, and you set their "permissions in locales" to be "en,jp" they'll be mod2 in en and jp and mod1 in de.

**Comment by kelimuttu** [comment]
Aah, got it. Thanks for clarifying. I think this should be closed, then.
