### ISSUE TITLE
Sign up page doesn't handle form errors

### ISSUE THREAD

**Issue by kaedroho** [mozilla/m-response#94]
Currently, if there's a form validation error, the user is sent back to step one and must fill in the form from scratch.

**Comment by NathHorrigan** [comment]
duplicate ticket #66

**Comment by kaedroho** [comment]
Really? That ticket only discusses the rules around password validation. It does not mention this issue.

Also, this isn't specific to passwords, try an invalid email address.

**Comment by NathHorrigan** [comment]
I could of been alot more detailed; This was discussed in standup/slack and the issue is caused by the the way Auth0 works. It check the signup details and then redirects the user to a `/callback` endpoint which then checks for an error in the url and then redirects the user back to the login page (with an error if there is one). 

The current solution is to focus on password validation by replicating the rules that are enforced by Auth0 in the react template (component already has validation support, it just needs updating with rules).
